name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        # References:
        # - https://github.com/APN-Pucky/gentoo-prefix-tester/blob/a80444a9486cde3380556f5125eef2e295a02e18/actions/kvm/action.yml#L35-L71
        # - https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/
        # - https://github.com/jonashackt/vagrant-github-actions/issues/5#issuecomment-2111798487
        shell: bash
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update
          sudo apt-get install -y virtualbox vagrant

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Vagrant boxes
        id: cache-vagrant
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles( 'Vagrantfile' ) }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - run: vagrant --version

      - name: Generate SSH key
        run: ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519

      - name: Explicitly set network bridge config
        # Otherwise vagrant asks for this assuming a TTY (despite `--no-tty` :()
        run: |
          sed -i 's/config.vm.network "public_network"/config.vm.network "public_network", bridge: "eth0"/' Vagrantfile

      - run: vagrant up --provision --no-tty

      - run: ./scripts/check-pages.py
